{{- $top := . -}}
{{- if eq $top.Values.commonConfig.resourceKind "Rollout"}}
{{- range $deployment := .Values.deploymentList -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}-preview
  labels:
    {{ $deployment.name }}-preview
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ $deployment.name }}
{{- end}}
---
{{- end}}